# keystone_consensus.py — the agreement rules, lifted out to be copied.
#
# GENERATED by scripts/lift.py from contracts/keystone.py. Do not edit by hand:
# tests/test_logic.py compares the two parsed trees function by function, so an
# edit here fails the suite rather than quietly claiming a provenance it does
# not have.
#
# GenLayer contracts run as ONE Python file inside the GenVM. There is no pip
# install and no cross-file import at deploy time, so this is not a module you
# import: it is a curated block. contracts/keystone.py already inlines these
# helpers. This file exists so the rules can be read and lifted into another
# project without reading a whole contract first.
#
# Everything here is pure. No storage, no network, no model. That is the point:
# these are the functions a validator runs to decide whether two nodes agreed,
# and a function that decides agreement must be deterministic or it decides
# nothing at all.
#
# keystone_agrees is SYMMETRIC: agrees(a, b) == agrees(b, a). An asymmetric
# agreement rule makes consensus depend on who happened to be elected leader,
# which is a subtle and very unpleasant bug.
#
# Two ideas are worth lifting. settle() asks the same pair in both presentation
# orders and folds the leader's OWN position bias into `neither` before any
# node compares anything, so the uncertainty is carried by the value that gets
# stored rather than by a tolerance in the agreement rule. A tolerant rule lets
# two nodes settle while privately disagreeing about which step blocks which.
#
# would_cycle() is the other. Every edge in a loop was agreed by the network,
# and the set of them is still impossible. Agreement is not consistency, and
# only the contract holds enough state to tell the difference.


# ---------------------------------------------------------------------------
# Deterministic helpers. Pure, module level, unit tested in tests/test_logic.py
# ---------------------------------------------------------------------------

FIRST = "first"        # the first item shown must come before the second
SECOND = "second"      # the second item shown must come before the first
NEITHER = "neither"    # no dependency either way, or the leader was not stable
TOKENS = (FIRST, SECOND, NEITHER)
BEFORE = "before"      # stored edge: a comes before b
AFTER = "after"        # stored edge: b comes before a
UNRELATED = "unrelated"
CYCLE = "cycle"        # refused: storing this would close a loop
OUTCOMES = (BEFORE, AFTER, UNRELATED, CYCLE)
MAX_STEPS = 24         # per plan, so the layering stays bounded
MAX_DELEGATES = 16
MAX_STEP_TEXT = 300
MAX_TITLE = 120
MAX_REASON = 160


def looks_like_address(raw):
    """Is this a 20 byte hex address, before anything tries to parse it?

    Address() raises a bare Exception on a malformed value, which the runtime
    reports as a contract error rather than as the caller's mistake. Checking
    the shape first turns "the contract crashed" into "that is not an address".
    """
    s = str(raw).strip()
    if len(s) != 42 or not s.startswith("0x"):
        return False
    for ch in s[2:]:
        if ch not in "0123456789abcdefABCDEF":
            return False
    return True


def normalise_token(raw):
    """One model answer to a legal token, or empty for anything unusable.

    Empty rather than a guess. A token invented here would be indistinguishable
    downstream from one the model actually returned, and it would be wrong on
    exactly the pairs the model found hardest.
    """
    s = str(raw).strip().lower()
    if s in TOKENS:
        return s
    return ""


def flip(token):
    """The same answer, read from the other end.

    Used to compare two presentation orders. `neither` is its own mirror, which
    is the only reason a stable `neither` is distinguishable from an unstable
    pair: both passes must SAY neither, rather than one saying it and the other
    being ignored.
    """
    if token == FIRST:
        return SECOND
    if token == SECOND:
        return FIRST
    if token == NEITHER:
        return NEITHER
    return ""


def settle(forward, reverse):
    """Fold the leader's own two presentation orders into ONE stored token.

    This is the whole design in three lines. The pair is asked in both orders
    and the answers must describe the same dependency; a pair the leader
    answers two different ways is not a close call, it is position bias, and it
    becomes `neither` HERE, before any node compares anything.

    Putting the uncertainty in the VALUE rather than in a tolerance in the
    agreement rule is deliberate. A rule that forgave a mismatch would let two
    nodes settle while privately disagreeing about which step blocks which, and
    the stored plan would read as decisive.
    """
    f = normalise_token(forward)
    r = normalise_token(reverse)
    if f == "" or r == "":
        return NEITHER
    if flip(f) == r:
        return f
    return NEITHER


def keystone_agrees(mine, theirs):
    """Layer 2. Exact equality on the settled token, and nothing else.

    Symmetric by construction: both sides are normalised the same way and the
    comparison is an equality, so agrees(a, b) == agrees(b, a). An asymmetric
    agreement rule makes consensus depend on who happened to be elected leader.

    There is deliberately no tolerance. Two nodes that order a pair opposite
    ways have agreed about nothing, and `neither` against `first` is a real
    disagreement about whether a dependency exists at all.
    """
    a = normalise_token(mine)
    b = normalise_token(theirs)
    if a == "" or b == "":
        return False
    return a == b


def structurally_sound(token, claimed_a, claimed_b, a, b):
    """Layer 1 of the validator. Costs nothing, runs before any prompt.

    Two ways a proposal is malformed regardless of what any model thinks: a
    token that is not one of the three, or an answer about a different pair
    from the one this transaction is deciding. The second matters more than it
    looks: without it a leader could answer an easy pair and have it recorded
    against a hard one.
    """
    if normalise_token(token) == "":
        return False
    return int(claimed_a) == int(a) and int(claimed_b) == int(b)


def reaches(edges, start, goal, n):
    """Is `goal` reachable from `start` by following stored edges?

    Plain breadth first search over a list of (from, to) pairs. This is the
    cycle test: an edge a -> b may only be stored when b cannot already reach
    a, because storing it would close a loop and the result would no longer be
    an ordering at all.

    Bounded by n, so a malformed edge list cannot spin. Pure, total, and the
    single most important function in the contract, because it is the part no
    model is involved in.
    """
    if start == goal:
        return True
    seen = [False] * n
    if start < 0 or start >= n:
        return False
    seen[start] = True
    frontier = [start]
    for _ in range(n):
        nxt = []
        for node in frontier:
            for (src, dst) in edges:
                if src != node or dst < 0 or dst >= n:
                    continue
                if dst == goal:
                    return True
                if not seen[dst]:
                    seen[dst] = True
                    nxt.append(dst)
        if len(nxt) == 0:
            return False
        frontier = nxt
    return False


def would_cycle(edges, a, b, n):
    """Would storing a -> b contradict what is already stored?

    True exactly when b already reaches a. That is the definition of the
    failure this contract exists for: every edge involved was agreed by the
    network, and the set of them is impossible.
    """
    return reaches(edges, b, a, n)


def layers(edges, n):
    """Kahn's algorithm, returning LAYERS rather than a single line.

    Everything in layer 0 can start now. Everything in layer 1 waits only for
    layer 0. A plan that is genuinely partly parallel has a partial order, and
    flattening it into one sequence would state a dependency nobody agreed to.

    Indices are sorted WITHIN each layer. Two nodes that compute the same
    layering but emit a tied pair in a different order would produce different
    strings from the same graph, which would defeat the point of deriving the
    answer deterministically at all.

    Returns None if the graph has a cycle. It should not be able to, because
    every edge was checked before it was stored, so None here means something
    upstream is broken and the caller should hear about it rather than receive
    a partial answer.
    """
    indegree = [0] * n
    for (src, dst) in edges:
        if 0 <= dst < n and 0 <= src < n:
            indegree[dst] = indegree[dst] + 1
    placed = 0
    out = []
    ready = sorted([i for i in range(n) if indegree[i] == 0])
    while len(ready) > 0:
        out.append(list(ready))
        placed = placed + len(ready)
        nxt = []
        for node in ready:
            for (src, dst) in edges:
                if src != node or not (0 <= dst < n):
                    continue
                indegree[dst] = indegree[dst] - 1
                if indegree[dst] == 0:
                    nxt.append(dst)
        ready = sorted(nxt)
    if placed != n:
        return None
    return out


def render_layers(lays):
    """Layers to a stable string: 0,2|1|3. Empty for an empty plan."""
    if lays is None:
        return ""
    return "|".join(",".join(str(i) for i in layer) for layer in lays)


def sanitise_reason(raw, limit=MAX_REASON):
    """Clean a leader supplied explanation before it is stored.

    These strings are NOT part of consensus, deliberately: two honest readers
    describe the same dependency differently, and comparing prose would stall
    every judgment. That means a leader chooses them freely, so they are
    treated as untrusted text on the way IN rather than on the way out.
    Nothing in this contract acts on them.
    """
    out = []
    for ch in str(raw):
        if ch in "<>{}\\`":
            continue
        if ord(ch) < 32 or ord(ch) == 127:
            ch = " "
        out.append(ch)
    return " ".join("".join(out).split())[:limit]


def clean_line(raw, limit):
    """A single line of caller text, whitespace collapsed, capped."""
    return " ".join(str(raw).split())[:limit]


def build_prompt(title, first_text, second_text):
    """One pair, in one presentation order.

    The order is carried by which step is called FIRST STEP, and the two calls
    differ only in that. Building both directions from one template is what
    makes the mirror meaningful: an asymmetry in the wording would look exactly
    like position bias and every pair would settle to `neither`.
    """
    return f"""You are sequencing work described in a plan called "{title}".

FIRST STEP:
{first_text}

SECOND STEP:
{second_text}

Does one of these have to be finished before the other can start?

Answer with exactly one word:

  first     THE FIRST STEP must be finished before the second can start.
  second    THE SECOND STEP must be finished before the first can start.
  neither   they can be done in either order, or at the same time.

Answer `neither` unless one genuinely cannot begin until the other is done.
Two steps that merely sound related, or that a person would happen to do in a
particular order out of habit, are `neither`. A real dependency is one where
doing them the other way round does not work.

Return json: {{"order": "first" or "second" or "neither", "because": "<= 25 words"}}"""
